# Generated by Django 2.0.5 on 2018-05-05 16:46

from django.db import migrations, models
import django.utils.timezone
import tool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(max_length=20)),
                ('cost_start', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cost_min', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cost_step', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cost_current', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('win', models.PositiveIntegerField(choices=[(0, 'PROCESS'), (1, 'WINNER'), (2, 'LOOSER')], default=tool.models.Status(0))),
            ],
            options={
                'ordering': ('published_date',),
            },
        ),
    ]
